[workspace]
authors = ["Tod Haren <104120984+tharen-odf@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "pynvel"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
numpy = ">=2.3.3,<3"
cython = ">=3.2.4,<4"
wheel = ">=0.45.1,<0.46"
setuptools = ">=80.9.0,<81"
setuptools_scm = ">=9.2.0,<10"
meson-python = ">=0.18.0,<0.19"
pytest = ">=8.4.2,<9"
ninja = ">=1.13.1,<2"
gcc = ">=15.2.0,<15.3"
gfortran = ">=15.2.0,<15.3"
gxx = ">=15.2.0,<15.3"
pip = ">=25.2,<26"
toml = ">=0.10.2,<0.11"
pandas = ">=2.3.3,<3"

[pypi-dependencies]
build = ">=1.3.0, <2"
ipykernel = ">=7.1.0, <8"
matplotlib = ">=3.10.8, <4"
